various fixes for temurin rpms, more coming for now ghost, binary, scriptlet, manpages  and permission tests should be fixed scriptlet now executed with correct arguments

diff --git a/utils/podman/dockerfiles/RunScriptlet b/utils/podman/dockerfiles/RunScriptlet
--- a/utils/podman/dockerfiles/RunScriptlet
+++ b/utils/podman/dockerfiles/RunScriptlet
@@ -10,6 +10,7 @@ COPY $FILE /tmp/$FILE
 
 # Example of an operation that will be run on any base image
 ARG EXECUTOR
-RUN $EXECUTOR /tmp/$FILE || echo "$FILE failed!!"
+ARG SCRIPTARG
+RUN $EXECUTOR /tmp/$FILE $SCRIPTARG || echo "$FILE failed!!"
 
 CMD ["bash"]
