scriptlet failures no longer prevent container creation

diff --git a/utils/mock/dockerfiles/RunScriptlet b/utils/mock/dockerfiles/RunScriptlet
--- a/utils/mock/dockerfiles/RunScriptlet
+++ b/utils/mock/dockerfiles/RunScriptlet
@@ -10,6 +10,6 @@ COPY $FILE /tmp/$FILE
 
 # Example of an operation that will be run on any base image
 ARG EXECUTOR
-RUN $EXECUTOR /tmp/$FILE
+RUN $EXECUTOR /tmp/$FILE || echo "$FILE failed!!"
 
 CMD ["bash"]
